version: '3.8'

services:
  # Postgres Database
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=restful-web-services-1
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - registry-network
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Service Registry (Eureka)
  service-registry:
    image: ravidobariya333/durgesh-ms1-service-registry:latest
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      - EUREKA_SERVER_HOST=service-registry
      - EUREKA_SERVER_PORT=8761
    networks:
      - registry-network
    restart: always
    volumes:
      - service-registry-data:/var/lib/service-registry

  # Config Server
  config-server:
    image: ravidobariya333/durgesh-ms1-config-server:latest
    container_name: config-server
    ports:
      - "8084:8084"
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    networks:
      - registry-network
    restart: always
    volumes:
      - config-server-data:/var/lib/config-server

  # Question Service
  question-service:
    image: ravidobariya333/durgesh-ms1-question-service:latest
    container_name: question-service
    ports:
      - "8092:8092"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restful-web-services-1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_CLOUD_CONFIG_SERVER_ENABLED=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
    depends_on:
      - postgres
    networks:
      - registry-network
    restart: always
    volumes:
      - question-service-data:/var/lib/question-service

  # Quiz Service
  quiz-service:
    image: ravidobariya333/durgesh-ms1-quiz-service:latest
    container_name: quiz-service
    ports:
      - "8091:8091"
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8084
      - SPRING_CLOUD_CONFIG_SERVER_ENABLED=true
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
    depends_on:
      - postgres
      - service-registry
      - config-server
      - question-service  
    networks:
      - registry-network
    restart: always
    volumes:
      - quiz-service-data:/var/lib/quiz-service

  # API Gateway
  api-gateway:
    image: ravidobariya333/durgesh-ms1-api-gateway:latest
    container_name: api-gateway
    ports:
      - "8093:8093"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://service-registry:8761/eureka/
      - SPRING_CLOUD_CONFIG_SERVER_ENABLED=true
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411
    depends_on:
      - service-registry
      - config-server
      - zipkin
    networks:
      - registry-network
    restart: always
    volumes:
      - api-gateway-data:/var/lib/api-gateway

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - registry-network
    restart: always

networks:
  registry-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  config-server-data:
    driver: local
  service-registry-data:
    driver: local
  question-service-data:
    driver: local
  quiz-service-data:
    driver: local
  api-gateway-data:
    driver: local
